  SPRITE_LIST automat
              "animweap/auto/pos1.bmp"     28
              "animweap/auto/pos2.bmp"     28
              "animweap/auto/pos3.bmp"     28
              "animweap/auto/fire1.bmp"    28
              "animweap/auto/fire2.bmp"    28
              "animweap/auto/fire3.bmp"    28
              "animweap/auto/fire4.bmp"    28
              "animweap/auto/firepos1.bmp" 28
              "animweap/auto/firepos2.bmp" 28
  END
