  SPRITE_LIST duplet
              "animweap/duplet/pos1.bmp"     28
              "animweap/duplet/fire1.bmp"    28
              "animweap/duplet/fire2.bmp"    28
              "animweap/duplet/fire3.bmp"    28
              "animweap/duplet/fire4.bmp"    28
              "animweap/duplet/fire5.bmp"    28
              "animweap/duplet/fire6.bmp"    28
              "animweap/duplet/fire7.bmp"    28
              "animweap/duplet/fire8.bmp"    28
              "animweap/duplet/fire9.bmp"    28
              "animweap/duplet/fire10.bmp"    28
              "animweap/duplet/fire11.bmp"    28
  END
