  SPRITE_LIST killer
              "animweap/killer/pos1.bmp"     28
              "animweap/killer/pos2.bmp"     28
              "animweap/killer/pos3.bmp"     28
              "animweap/killer/pos4.bmp"     28
              "animweap/killer/pos5.bmp"     28
              "animweap/killer/pos6.bmp"     28
              "animweap/killer/pos7.bmp"     28
              "animweap/killer/pos8.bmp"     28
              "animweap/killer/pos9.bmp"     28
              "animweap/killer/pos10.bmp"    28
  END
