SPRITE_ANIMATION fak
              SPRITE            SPR_FAK
              CROSS             FALSE
              CHANGE_TIME       4
              ANIM              0 1 2 3 4 5 6 7
END

SPRITE_ANIMATION tree1
              SPRITE            SPR_TREE1
              CROSS             FALSE
              CHANGE_TIME       4
              ANIM              0
END

SPRITE_ANIMATION chair
              SPRITE            SPR_CHAIR
              CROSS             FALSE
              CHANGE_TIME       4
              ANIM              0
END

SPRITE_ANIMATION coat
              SPRITE            SPR_COAT
              CROSS             FALSE
              CHANGE_TIME       40
              ANIM              0
END
