  PLAYER      diablo
          SPRITE        SPR_POSS
          DEATH_SOUND   SND_DEATH1
          CROSS_SOUND   SND_PAIN25_1
          ATACK_SOUND   NOSOUND
          LUCK_SOUND    SND_PL_LUCK
          HEY_SOUND     SND_Z_PAIN
          DEATH_SPRITE  8 9 10 11
          ATACK_SPRITE  5 6
          NORM_SPRITE   0 1
          CROSS_SPRITE  7
          WEAPON_ID     GW_DUPLET
          WEAPON_CACHE  GAME_WEAPON_LIST
          ATACK         100
          FAR_FOLLOW    100
          NEAR_FOLLOW   100
          VIEW_OUT      100
          RANDOM_MOVE   100
          SPEED         0.6
  END
