  PLAYER      intel
          SPRITE        SPR_INTEL
          DEATH_SOUND   SND_DEATH1
          CROSS_SOUND   SND_PAIN25_1
          ATACK_SOUND   NOSOUND
          LUCK_SOUND    NOSOUND
          HEY_SOUND     SND_Z_PAIN
          DEATH_SPRITE  6 7 8 9 10 11 12 13 14
          ATACK_SPRITE  2 3 4 5
          NORM_SPRITE   0 1
          CROSS_SPRITE  1
          WEAPON_ID     GW_DUPLET
          WEAPON_CACHE  GAME_WEAPON_LIST
          ATACK         100
          FAR_FOLLOW    50
          NEAR_FOLLOW   110
          VIEW_OUT      10
          RANDOM_MOVE   10
          SPEED         0.4
  END
