  PLAYER      play
          SPRITE        SPR_PLAY
          DEATH_SOUND   SND_PL_DEATH
          CROSS_SOUND   SND_PL_CROSS
          ATACK_SOUND   NOSOUND
          HEY_SOUND     SND_PL_HEY
          LUCK_SOUND    SND_PL_EXC
          DEATH_SPRITE  8 9 10 12
          ATACK_SPRITE  5 6
          NORM_SPRITE   0 1
          CROSS_SPRITE  7
          WEAPON_ID     GW_BAZUKA
          WEAPON_CACHE  GAME_WEAPON_LIST
          SPEED         0.25
  END
