  PLAYER      sarg
          SPRITE        SPR_SARG
          DEATH_SOUND   SND_DEATH1
          CROSS_SOUND   SND_PAIN25_1
          ATACK_SOUND   NOSOUND
          LUCK_SOUND    NOSOUND
          HEY_SOUND     SND_Z_PAIN
          DEATH_SPRITE  8 9 10 11
          ATACK_SPRITE  5 6
          NORM_SPRITE   0 1
          CROSS_SPRITE  7
          WEAPON_ID     GW_KILLER
          WEAPON_CACHE  GAME_WEAPON_LIST
          ATACK         120
          FAR_FOLLOW    100
          NEAR_FOLLOW   110
          VIEW_OUT      100
          RANDOM_MOVE   100
          SPEED         0.3
  END
