  REM Данный таг должен ОБЯЗАТЕЛЬНО присутсвовать
  REM Таблица экземпляров

  SUBJECT_MAP sbj_map 256
          DOOR           GAME_OTHERS_LIST   OTH_DOOR1      4  4   WEST
          SUBJECT        GAME_SUBJECT_LIST  SBJ_KILLER     6  1
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      8  23  0 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      24  20 1 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      40  22 2 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      56  19 3 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      23  27 4 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      39  34 5 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      53  34 6 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      44  42 7 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      33 47  12 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      17  47  13 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      22  52  14 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      34  56  15 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      34  59  16 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      5  51  17 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      9  36  18 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      23  37  19 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      23  39  20 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      52  5  21 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      57  60  22 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      20  7  23 50 0
          PLAYER         GAME_PLAYER_LIST   PL_MONSTR      20  51  24 50 0
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      41  10  90 250 100
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      43  10  90 250 100
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      45  10  90 250 100
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  12  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  13  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  14  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  15  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  16  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  17  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  18  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  19  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       52  20  90 150 180
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       36  39  190 50 90
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       37  39  190 50 90
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       38  39  190 50 90
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       39  39  190 50 90
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       40  39  190 50 90
          PLAYER         GAME_PLAYER_LIST   PL_INTEL       41  39  190 50 90
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      36  44  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      37  44  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      38  44  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      39  44  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      40  44  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      41  44  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      8   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO      9   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     10   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     11   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     12   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     13   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     14   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     15   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     16   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     17   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     18   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_DIABLO     19   61  90 250 270
          PLAYER         GAME_PLAYER_LIST   PL_SARG       13   5   100 30  90
          PLAYER         GAME_PLAYER_LIST   PL_SARG       14   5   100 30  90
          PLAYER         GAME_PLAYER_LIST   PL_SARG       15   5   100 30  90
          PLAYER         GAME_PLAYER_LIST   PL_SARG       16   5   100 30  90
          PLAYER         GAME_PLAYER_LIST   PL_SARG       17   5   100 30  90
          PLAYER         GAME_PLAYER_LIST   PL_SARG       18   5   100 30  90
          PLAYER         GAME_PLAYER_LIST   PL_SARG       19   5   100 30  90
          PLAYER         GAME_PLAYER_LIST   PL_SARG       20   5   100 30  90
          PORTAL         GAME_TELEPORT_LIST TLP_PORTAL1    6   4   0  0  TRUE "maps/wolf3d/wolf3d.lev"
  END
