  REM Описание спрайтов

  DEST "sprites/3d"

  REM INCLUDE "source/include/graph/sprites/3d/armor.inc"
  REM INCLUDE "source/include/graph/sprites/3d/automat.inc"
  REM INCLUDE "source/include/graph/sprites/3d/doom.inc"
  REM INCLUDE "source/include/graph/sprites/3d/duplet.inc"
  REM INCLUDE "source/include/graph/sprites/3d/gun.inc"
  REM INCLUDE "source/include/graph/sprites/3d/health.inc"
  REM INCLUDE "source/include/graph/sprites/3d/killer.inc"
  REM INCLUDE "source/include/graph/sprites/3d/portal.inc"
  REM INCLUDE "source/include/graph/sprites/3d/armor.inc"
  REM INCLUDE "source/include/graph/sprites/3d/fak.inc"
  REM INCLUDE "source/include/graph/sprites/3d/intel.inc"
  REM INCLUDE "source/include/graph/sprites/3d/chuv.inc"
  REM INCLUDE "source/include/graph/sprites/3d/sprite.inc"
  REM INCLUDE "source/include/graph/sprites/3d/tree1.inc"
  REM INCLUDE "source/include/graph/sprites/3d/bazuka.inc"
  REM INCLUDE "source/include/graph/sprites/3d/bpat.inc"
  REM INCLUDE "source/include/graph/sprites/3d/chair.inc"
  REM INCLUDE "source/include/graph/sprites/3d/krest1.inc"
  REM INCLUDE "source/include/graph/sprites/3d/coat.inc"

  DEST "sprites/2d"

  REM INCLUDE "source/include/graph/sprites/2d/automat.inc"
  REM INCLUDE "source/include/graph/sprites/2d/bazuka.inc"
  REM INCLUDE "source/include/graph/sprites/2d/ch_face.inc"
  REM INCLUDE "source/include/graph/sprites/2d/duplet.inc"
  REM INCLUDE "source/include/graph/sprites/2d/gun.inc"
  REM INCLUDE "source/include/graph/sprites/2d/iface.inc"
  REM INCLUDE "source/include/graph/sprites/2d/killer.inc"
  REM INCLUDE "source/include/graph/sprites/2d/sight.inc"

  REM Описание текстур

  DEST "textures"

  REM INCLUDE "source/include/graph/textures/text.inc"
