  WEAPON        automat
                SHOT
                     FLY_SND    NOSOUND
                     BAH_SND    SND_MG_BAH
                     FORCE      15
                     SPEED      4.5
                     MAX_DIST   64
                     SPRITES    SPR_PUFF
                     RADIUS     2
                     BAH_ANIM   0 1 2 3
                     FLY_ANIM   -1 -1
                     BACK_FORCE FALSE
                END
         BOX            BOX_AUTOMAT
         SPEED          15
         FIRST_COUNT    100
         MAX_COUNT      250

         P_SOUND        NOSOUND
         A_SOUND        SND_MG_FIRE
         P_ANIM         0 1 2
         A_ANIM         3 4 5 6
         P_CHANGE_TIME  50
         A_CHANGE_TIME  15
         SPRITES        SL_AUTOMAT
  END
