  WEAPON        auto_pos
                SHOT
                     FLY_SND    NOSOUND
                     BAH_SND    SND_MG_BAH
                     FORCE      20
                     SPEED      4.5
                     MAX_DIST   64
                     SPRITES    SPR_PUFF
                     RADIUS     2
                     BAH_ANIM   0 1 2 3
                     FLY_ANIM   -1 -1
                     BACK_FORCE FALSE
                END
         BOX            BOX_AUTOMAT
         SPEED          100
         FIRST_COUNT    40
         MAX_COUNT      250

         P_SOUND        NOSOUND
         A_SOUND        SND_MG_FIRE
         P_ANIM         0 1 2
         A_ANIM         7 8
         P_CHANGE_TIME  50
         A_CHANGE_TIME  50
         SPRITES        SL_AUTOMAT
  END
