  WEAPON        bazuka
                SHOT
                     FLY_SND    SND_SKM_FLY
                     BAH_SND    SND_SKM_BAH
                     FORCE      420
                     SPEED      1.9
                     MAX_DIST   64
                     SPRITES    SPR_BPAT
                     RADIUS     10
                     BAH_ANIM   1 2 3 4 5 6
                     FLY_ANIM   0
                     BACK_FORCE TRUE
                END
         BOX            BOX_FB
         SPEED          75
         FIRST_COUNT    10
         MAX_COUNT      12

         P_SOUND        NOSOUND
         A_SOUND        SND_MG_FIRE
         P_ANIM         0 1 2 3 4 5 6 7
         A_ANIM         0 1 2 3 4 5 6 7
         P_CHANGE_TIME  15
         A_CHANGE_TIME  50
         SPRITES        SL_BAZUKA
  END
