  WEAPON        gun
                SHOT
                     FLY_SND    NOSOUND
                     BAH_SND    NOSOUND
                     FORCE      20
                     SPEED      2.5
                     MAX_DIST   16
                     SPRITES    SPR_PUFF
                     RADIUS     1
                     BAH_ANIM   0 1 2 3
                     FLY_ANIM   -1 -1
                     BACK_FORCE FALSE
                END
         BOX            BOX_GUN
         SPEED          100
         FIRST_COUNT    25
         MAX_COUNT      80

         P_SOUND        NOSOUND
         A_SOUND        SND_MG_FIRE
         P_ANIM         0 0
         A_ANIM         1 2 3
         P_CHANGE_TIME  50
         A_CHANGE_TIME  25
         SPRITES        SL_GUN
  END
