  WEAPON        killer
                SHOT
                     FLY_SND    SND_KL_FLY
                     BAH_SND    SND_KL_BAH
                     FORCE      65
                     SPEED      1.5
                     MAX_DIST   2
                     SPRITES    NOSPRITE
                     RADIUS     2
                     BAH_ANIM   -1
                     FLY_ANIM   -1
                     BACK_FORCE FALSE
                END
         BOX            BOX_KILLER
         SPEED          75
         FIRST_COUNT    -1
         MAX_COUNT      10000

         P_SOUND        NOSOUND
         A_SOUND        SND_KL_FIRE
         P_ANIM         0 0
         A_ANIM         0 1 2 3 4 5 6 7 8 9 6 5 2
         P_CHANGE_TIME  50
         A_CHANGE_TIME  3
         SPRITES        SL_KILLER
  END
