  WEAPON        duplet
                SHOT
                     FLY_SND    NOSOUND
                     BAH_SND    SND_MG_BAH
                     FORCE      75
                     SPEED      2.5
                     MAX_DIST   32
                     SPRITES    SPR_PISF
                     RADIUS     4
                     BAH_ANIM   0 1 2 3
                     FLY_ANIM   -1 -1
                     BACK_FORCE FALSE
                END
         BOX            BOX_SHOTGUN
         SPEED          95
         FIRST_COUNT    40
         MAX_COUNT      100

         P_SOUND        SND_1
         A_SOUND        SND_SGUN_USE
         P_ANIM         0 0
         A_ANIM         1 2 3 4 5 6 7 8 9 10 11
         P_CHANGE_TIME  50
         A_CHANGE_TIME  7
         SPRITES        SL_DUPLET
  END
