  WEAPON        skmat
                SHOT
                     FLY_SND    SND_SKM_FLY
                     BAH_SND    SND_SKM_BAH
                     FORCE      45
                     SPEED      1.9
                     MAX_DIST   64
                     SPRITES    SPR_BAL1
                     RADIUS     1
                     BAH_ANIM   1 2 3
                     FLY_ANIM   0
                     BACK_FORCE FALSE
                END
         BOX            BOX_SHOTGUN
         SPEED          100
         FIRST_COUNT    40
         MAX_COUNT      100

         P_SOUND        NOSOUND
         A_SOUND        SND_SKM_FIRE
         P_ANIM         0 1 2
         A_ANIM         7 8
         P_CHANGE_TIME  50
         A_CHANGE_TIME  50
         SPRITES        SL_AUTOMAT
  END
