  SPRITE automat 1
    FACE 0 8
      IMAGE "sprites/guns/auto/_auto8.bmp" 0 28
      IMAGE "sprites/guns/auto/_auto7.bmp" 1 28
      IMAGE "sprites/guns/auto/_auto6.bmp" 2 28
      IMAGE "sprites/guns/auto/_auto5.bmp" 3 28
      IMAGE "sprites/guns/auto/_auto4.bmp" 4 28
      IMAGE "sprites/guns/auto/_auto3.bmp" 5 28
      IMAGE "sprites/guns/auto/_auto2.bmp" 6 28
      IMAGE "sprites/guns/auto/_auto1.bmp" 7 28
    END
  END
  