  SPRITE bazuka 1
    FACE 0 8
      IMAGE "sprites/guns/bazuka/baz8.bmp" 0 28
      IMAGE "sprites/guns/bazuka/baz7.bmp" 1 28
      IMAGE "sprites/guns/bazuka/baz6.bmp" 2 28
      IMAGE "sprites/guns/bazuka/baz5.bmp" 3 28
      IMAGE "sprites/guns/bazuka/baz4.bmp" 4 28
      IMAGE "sprites/guns/bazuka/baz3.bmp" 5 28
      IMAGE "sprites/guns/bazuka/baz2.bmp" 6 28
      IMAGE "sprites/guns/bazuka/baz1.bmp" 7 28
    END
  END
  