  SPRITE bpat 7
    FACE 0 8
      IMAGE "sprites/patrons/bazuka/bpat1.bmp" 7 28
      IMAGE "sprites/patrons/bazuka/bpat2.bmp" 0 28
      IMAGE "sprites/patrons/bazuka/bpat3.bmp" 1 28
      IMAGE "sprites/patrons/bazuka/bpat4.bmp" 2 28
      IMAGE "sprites/patrons/bazuka/bpat5.bmp" 3 28
      IMAGE "sprites/patrons/bazuka/bpat6.bmp" 4 28
      IMAGE "sprites/patrons/bazuka/bpat7.bmp" 5 28
      IMAGE "sprites/patrons/bazuka/bpat8.bmp" 6 28
    END
    FACE 1 1
      IMAGE "sprites/patrons/bazuka/ex1.bmp" 0 28
    END
    FACE 2 1
      IMAGE "sprites/patrons/bazuka/ex2.bmp" 0 28
    END
    FACE 3 1
      IMAGE "sprites/patrons/bazuka/ex3.bmp" 0 28
    END
    FACE 4 1
      IMAGE "sprites/patrons/bazuka/ex4.bmp" 0 28
    END
    FACE 5 1
      IMAGE "sprites/patrons/bazuka/ex5.bmp" 0 28
    END
    FACE 6 1
      IMAGE "sprites/patrons/bazuka/ex6.bmp" 0 28
    END
  END

