  SPRITE chair 1
    FACE 0 8
      IMAGE "sprites/world/chair/ch1.bmp" 0 28
      IMAGE "sprites/world/chair/ch2.bmp" 1 28
      IMAGE "sprites/world/chair/ch3.bmp" 2 28
      IMAGE "sprites/world/chair/ch4.bmp" 3 28
      IMAGE "sprites/world/chair/ch5.bmp" 4 28
      IMAGE "sprites/world/chair/ch6.bmp" 5 28
      IMAGE "sprites/world/chair/ch7.bmp" 6 28
      IMAGE "sprites/world/chair/ch8.bmp" 7 28
    END
  END
