  SPRITE chuv 8
    FACE 0 8
      IMAGE "sprites/models/men/go1/1go0000.bmp" 7 28
      IMAGE "sprites/models/men/go1/1go0012.bmp" 6 28
      IMAGE "sprites/models/men/go1/1go0025.bmp" 5 28
      IMAGE "sprites/models/men/go1/1go0037.bmp" 4 28
      IMAGE "sprites/models/men/go1/1go0050.bmp" 3 28
      IMAGE "sprites/models/men/go1/1go0062.bmp" 2 28
      IMAGE "sprites/models/men/go1/1go0075.bmp" 1 28
      IMAGE "sprites/models/men/go1/1go0087.bmp" 0 28
    END
    FACE 1 8
      IMAGE "sprites/models/men/go2/2go0000.bmp" 7 28
      IMAGE "sprites/models/men/go2/2go0012.bmp" 6 28
      IMAGE "sprites/models/men/go2/2go0025.bmp" 5 28
      IMAGE "sprites/models/men/go2/2go0037.bmp" 4 28
      IMAGE "sprites/models/men/go2/2go0050.bmp" 3 28
      IMAGE "sprites/models/men/go2/2go0062.bmp" 2 28
      IMAGE "sprites/models/men/go2/2go0075.bmp" 1 28
      IMAGE "sprites/models/men/go2/2go0087.bmp" 0 28
    END
    FACE 2 8
      IMAGE "sprites/models/men/stay/st0000.bmp" 7 28
      IMAGE "sprites/models/men/stay/st0012.bmp" 6 28
      IMAGE "sprites/models/men/stay/st0025.bmp" 5 28
      IMAGE "sprites/models/men/stay/st0037.bmp" 4 28
      IMAGE "sprites/models/men/stay/st0050.bmp" 3 28
      IMAGE "sprites/models/men/stay/st0062.bmp" 2 28
      IMAGE "sprites/models/men/stay/st0075.bmp" 1 28
      IMAGE "sprites/models/men/stay/st0087.bmp" 0 28
    END
    FACE 3 8
      IMAGE "sprites/models/men/fir0/ofi0000.bmp" 7 28
      IMAGE "sprites/models/men/fir0/ofi0012.bmp" 6 28
      IMAGE "sprites/models/men/fir0/ofi0025.bmp" 5 28
      IMAGE "sprites/models/men/fir0/ofi0037.bmp" 4 28
      IMAGE "sprites/models/men/fir0/ofi0050.bmp" 3 28
      IMAGE "sprites/models/men/fir0/ofi0062.bmp" 2 28
      IMAGE "sprites/models/men/fir0/ofi0075.bmp" 1 28
      IMAGE "sprites/models/men/fir0/ofi0087.bmp" 0 28
    END
    FACE 4 8
      IMAGE "sprites/models/men/fir1/1fi0000.bmp" 7 28
      IMAGE "sprites/models/men/fir1/1fi0012.bmp" 6 28
      IMAGE "sprites/models/men/fir1/1fi0025.bmp" 5 28
      IMAGE "sprites/models/men/fir1/1fi0037.bmp" 4 28
      IMAGE "sprites/models/men/fir1/1fi0050.bmp" 3 28
      IMAGE "sprites/models/men/fir1/1fi0062.bmp" 2 28
      IMAGE "sprites/models/men/fir1/1fi0075.bmp" 1 28
      IMAGE "sprites/models/men/fir1/1fi0087.bmp" 0 28
    END
    FACE 5 8
      IMAGE "sprites/models/men/die1/1di0000.bmp" 7 28
      IMAGE "sprites/models/men/die1/1di0012.bmp" 6 28
      IMAGE "sprites/models/men/die1/1di0025.bmp" 5 28
      IMAGE "sprites/models/men/die1/1di0037.bmp" 4 28
      IMAGE "sprites/models/men/die1/1di0050.bmp" 3 28
      IMAGE "sprites/models/men/die1/1di0062.bmp" 2 28
      IMAGE "sprites/models/men/die1/1di0075.bmp" 1 28
      IMAGE "sprites/models/men/die1/1di0087.bmp" 0 28
    END
    FACE 6 8
      IMAGE "sprites/models/men/die2/2di0000.bmp" 7 28
      IMAGE "sprites/models/men/die2/2di0012.bmp" 6 28
      IMAGE "sprites/models/men/die2/2di0025.bmp" 5 28
      IMAGE "sprites/models/men/die2/2di0037.bmp" 4 28
      IMAGE "sprites/models/men/die2/2di0050.bmp" 3 28
      IMAGE "sprites/models/men/die2/2di0062.bmp" 2 28
      IMAGE "sprites/models/men/die2/2di0075.bmp" 1 28
      IMAGE "sprites/models/men/die2/2di0087.bmp" 0 28
    END
    FACE 7 8
      IMAGE "sprites/models/men/die3/3di0000.bmp" 7 28
      IMAGE "sprites/models/men/die3/3di0012.bmp" 6 28
      IMAGE "sprites/models/men/die3/3di0025.bmp" 5 28
      IMAGE "sprites/models/men/die3/3di0037.bmp" 4 28
      IMAGE "sprites/models/men/die3/3di0050.bmp" 3 28
      IMAGE "sprites/models/men/die3/3di0062.bmp" 2 28
      IMAGE "sprites/models/men/die3/3di0075.bmp" 1 28
      IMAGE "sprites/models/men/die3/3di0087.bmp" 0 28
    END
  END
