  SPRITE duplet 1
    FACE 0 8
      IMAGE "sprites/guns/duplet/_duplet8.bmp" 0 28
      IMAGE "sprites/guns/duplet/_duplet7.bmp" 1 28
      IMAGE "sprites/guns/duplet/_duplet6.bmp" 2 28
      IMAGE "sprites/guns/duplet/_duplet5.bmp" 3 28
      IMAGE "sprites/guns/duplet/_duplet4.bmp" 4 28
      IMAGE "sprites/guns/duplet/_duplet3.bmp" 5 28
      IMAGE "sprites/guns/duplet/_duplet2.bmp" 6 28
      IMAGE "sprites/guns/duplet/_duplet1.bmp" 7 28
    END
  END
  