  SPRITE fak 8
    FACE 0 1
      IMAGE "sprites/world/lights/fakel/faza1/fakel101.bmp" 0 28
    END
    FACE 1 1
      IMAGE "sprites/world/lights/fakel/faza1/fakel102.bmp" 0 28
    END
    FACE 2 1
      IMAGE "sprites/world/lights/fakel/faza1/fakel103.bmp" 0 28
    END
    FACE 3 1
      IMAGE "sprites/world/lights/fakel/faza1/fakel104.bmp" 0 28
    END
    FACE 4 1
      IMAGE "sprites/world/lights/fakel/faza1/fakel105.bmp" 0 28
    END
    FACE 5 1
      IMAGE "sprites/world/lights/fakel/faza1/fakel106.bmp" 0 28
    END
    FACE 6 1
      IMAGE "sprites/world/lights/fakel/faza1/fakel107.bmp" 0 28
    END
    FACE 7 1
      IMAGE "sprites/world/lights/fakel/faza1/fakel108.bmp" 0 28
    END
  END
