  SPRITE gun 1
    FACE 0 8
      IMAGE "sprites/guns/gun/_gun8.bmp" 0 28
      IMAGE "sprites/guns/gun/_gun7.bmp" 1 28
      IMAGE "sprites/guns/gun/_gun6.bmp" 2 28
      IMAGE "sprites/guns/gun/_gun5.bmp" 3 28
      IMAGE "sprites/guns/gun/_gun4.bmp" 4 28
      IMAGE "sprites/guns/gun/_gun3.bmp" 5 28
      IMAGE "sprites/guns/gun/_gun2.bmp" 6 28
      IMAGE "sprites/guns/gun/_gun1.bmp" 7 28
    END
  END
  