  SPRITE intel 15
    FACE 0 8
      IMAGE "sprites/models/intel/run1/1run1.bmp" 7 28
      IMAGE "sprites/models/intel/run1/1run2.bmp" 6 28
      IMAGE "sprites/models/intel/run1/1run3.bmp" 5 28
      IMAGE "sprites/models/intel/run1/1run4.bmp" 4 28
      IMAGE "sprites/models/intel/run1/1run5.bmp" 3 28
      IMAGE "sprites/models/intel/run1/1run6.bmp" 2 28
      IMAGE "sprites/models/intel/run1/1run7.bmp" 1 28
      IMAGE "sprites/models/intel/run1/1run8.bmp" 0 28
    END
    FACE 1 8
      IMAGE "sprites/models/intel/run2/2run1.bmp" 7 28
      IMAGE "sprites/models/intel/run2/2run2.bmp" 6 28
      IMAGE "sprites/models/intel/run2/2run3.bmp" 5 28
      IMAGE "sprites/models/intel/run2/2run4.bmp" 4 28
      IMAGE "sprites/models/intel/run2/2run5.bmp" 3 28
      IMAGE "sprites/models/intel/run2/2run6.bmp" 2 28
      IMAGE "sprites/models/intel/run2/2run7.bmp" 1 28
      IMAGE "sprites/models/intel/run2/2run8.bmp" 0 28
    END
    FACE 2 8
      IMAGE "sprites/models/intel/faza1/1faza1.bmp" 7 28
      IMAGE "sprites/models/intel/faza1/1faza2.bmp" 6 28
      IMAGE "sprites/models/intel/faza1/1faza3.bmp" 5 28
      IMAGE "sprites/models/intel/faza1/1faza4.bmp" 4 28
      IMAGE "sprites/models/intel/faza1/1faza5.bmp" 3 28
      IMAGE "sprites/models/intel/faza1/1faza6.bmp" 2 28
      IMAGE "sprites/models/intel/faza1/1faza7.bmp" 1 28
      IMAGE "sprites/models/intel/faza1/1faza8.bmp" 0 28
    END
    FACE 3 8
      IMAGE "sprites/models/intel/faza2/2faza1.bmp" 7 28
      IMAGE "sprites/models/intel/faza2/2faza2.bmp" 6 28
      IMAGE "sprites/models/intel/faza2/2faza3.bmp" 5 28
      IMAGE "sprites/models/intel/faza2/2faza4.bmp" 4 28
      IMAGE "sprites/models/intel/faza2/2faza5.bmp" 3 28
      IMAGE "sprites/models/intel/faza2/2faza6.bmp" 2 28
      IMAGE "sprites/models/intel/faza2/2faza7.bmp" 1 28
      IMAGE "sprites/models/intel/faza2/2faza8.bmp" 0 28
    END
    FACE 4 8
      IMAGE "sprites/models/intel/faza3/3faza1.bmp" 7 28
      IMAGE "sprites/models/intel/faza3/3faza2.bmp" 6 28
      IMAGE "sprites/models/intel/faza3/3faza3.bmp" 5 28
      IMAGE "sprites/models/intel/faza3/3faza4.bmp" 4 28
      IMAGE "sprites/models/intel/faza3/3faza5.bmp" 3 28
      IMAGE "sprites/models/intel/faza3/3faza6.bmp" 2 28
      IMAGE "sprites/models/intel/faza3/3faza7.bmp" 1 28
      IMAGE "sprites/models/intel/faza3/3faza8.bmp" 0 28
    END
    FACE 5 8
      IMAGE "sprites/models/intel/faza4/4faza1.bmp" 7 28
      IMAGE "sprites/models/intel/faza4/4faza2.bmp" 6 28
      IMAGE "sprites/models/intel/faza4/4faza3.bmp" 5 28
      IMAGE "sprites/models/intel/faza4/4faza4.bmp" 4 28
      IMAGE "sprites/models/intel/faza4/4faza5.bmp" 3 28
      IMAGE "sprites/models/intel/faza4/4faza6.bmp" 2 28
      IMAGE "sprites/models/intel/faza4/4faza7.bmp" 1 28
      IMAGE "sprites/models/intel/faza4/4faza8.bmp" 0 28
    END
    FACE 6 8
      IMAGE "sprites/models/intel/die1/1die1.bmp" 7 28
      IMAGE "sprites/models/intel/die1/1die2.bmp" 6 28
      IMAGE "sprites/models/intel/die1/1die3.bmp" 5 28
      IMAGE "sprites/models/intel/die1/1die4.bmp" 4 28
      IMAGE "sprites/models/intel/die1/1die5.bmp" 3 28
      IMAGE "sprites/models/intel/die1/1die6.bmp" 2 28
      IMAGE "sprites/models/intel/die1/1die7.bmp" 1 28
      IMAGE "sprites/models/intel/die1/1die8.bmp" 0 28
    END
    FACE 7 8
      IMAGE "sprites/models/intel/die2/2die1.bmp" 7 28
      IMAGE "sprites/models/intel/die2/2die2.bmp" 6 28
      IMAGE "sprites/models/intel/die2/2die3.bmp" 5 28
      IMAGE "sprites/models/intel/die2/2die4.bmp" 4 28
      IMAGE "sprites/models/intel/die2/2die5.bmp" 3 28
      IMAGE "sprites/models/intel/die2/2die6.bmp" 2 28
      IMAGE "sprites/models/intel/die2/2die7.bmp" 1 28
      IMAGE "sprites/models/intel/die2/2die8.bmp" 0 28
    END
    FACE 8 8
      IMAGE "sprites/models/intel/die3/3die1.bmp" 7 28
      IMAGE "sprites/models/intel/die3/3die2.bmp" 6 28
      IMAGE "sprites/models/intel/die3/3die3.bmp" 5 28
      IMAGE "sprites/models/intel/die3/3die4.bmp" 4 28
      IMAGE "sprites/models/intel/die3/3die5.bmp" 3 28
      IMAGE "sprites/models/intel/die3/3die6.bmp" 2 28
      IMAGE "sprites/models/intel/die3/3die7.bmp" 1 28
      IMAGE "sprites/models/intel/die3/3die8.bmp" 0 28
    END
    FACE 9 8
      IMAGE "sprites/models/intel/die4/4die1.bmp" 7 28
      IMAGE "sprites/models/intel/die4/4die2.bmp" 6 28
      IMAGE "sprites/models/intel/die4/4die3.bmp" 5 28
      IMAGE "sprites/models/intel/die4/4die4.bmp" 4 28
      IMAGE "sprites/models/intel/die4/4die5.bmp" 3 28
      IMAGE "sprites/models/intel/die4/4die6.bmp" 2 28
      IMAGE "sprites/models/intel/die4/4die7.bmp" 1 28
      IMAGE "sprites/models/intel/die4/4die8.bmp" 0 28
    END
    FACE 10 8
      IMAGE "sprites/models/intel/die5/5die1.bmp" 7 28
      IMAGE "sprites/models/intel/die5/5die2.bmp" 6 28
      IMAGE "sprites/models/intel/die5/5die3.bmp" 5 28
      IMAGE "sprites/models/intel/die5/5die4.bmp" 4 28
      IMAGE "sprites/models/intel/die5/5die5.bmp" 3 28
      IMAGE "sprites/models/intel/die5/5die6.bmp" 2 28
      IMAGE "sprites/models/intel/die5/5die7.bmp" 1 28
      IMAGE "sprites/models/intel/die5/5die8.bmp" 0 28
    END
    FACE 11 8
      IMAGE "sprites/models/intel/die6/6die1.bmp" 7 28
      IMAGE "sprites/models/intel/die6/6die2.bmp" 6 28
      IMAGE "sprites/models/intel/die6/6die3.bmp" 5 28
      IMAGE "sprites/models/intel/die6/6die4.bmp" 4 28
      IMAGE "sprites/models/intel/die6/6die5.bmp" 3 28
      IMAGE "sprites/models/intel/die6/6die6.bmp" 2 28
      IMAGE "sprites/models/intel/die6/6die7.bmp" 1 28
      IMAGE "sprites/models/intel/die6/6die8.bmp" 0 28
    END
    FACE 12 8
      IMAGE "sprites/models/intel/die7/7die1.bmp" 7 28
      IMAGE "sprites/models/intel/die7/7die2.bmp" 6 28
      IMAGE "sprites/models/intel/die7/7die3.bmp" 5 28
      IMAGE "sprites/models/intel/die7/7die4.bmp" 4 28
      IMAGE "sprites/models/intel/die7/7die5.bmp" 3 28
      IMAGE "sprites/models/intel/die7/7die6.bmp" 2 28
      IMAGE "sprites/models/intel/die7/7die7.bmp" 1 28
      IMAGE "sprites/models/intel/die7/7die8.bmp" 0 28
    END
    FACE 13 8
      IMAGE "sprites/models/intel/die8/8die1.bmp" 7 28
      IMAGE "sprites/models/intel/die8/8die2.bmp" 6 28
      IMAGE "sprites/models/intel/die8/8die3.bmp" 5 28
      IMAGE "sprites/models/intel/die8/8die4.bmp" 4 28
      IMAGE "sprites/models/intel/die8/8die5.bmp" 3 28
      IMAGE "sprites/models/intel/die8/8die6.bmp" 2 28
      IMAGE "sprites/models/intel/die8/8die7.bmp" 1 28
      IMAGE "sprites/models/intel/die8/8die8.bmp" 0 28
    END
    FACE 14 8
      IMAGE "sprites/models/intel/die9/9die1.bmp" 7 28
      IMAGE "sprites/models/intel/die9/9die2.bmp" 6 28
      IMAGE "sprites/models/intel/die9/9die3.bmp" 5 28
      IMAGE "sprites/models/intel/die9/9die4.bmp" 4 28
      IMAGE "sprites/models/intel/die9/9die5.bmp" 3 28
      IMAGE "sprites/models/intel/die9/9die6.bmp" 2 28
      IMAGE "sprites/models/intel/die9/9die7.bmp" 1 28
      IMAGE "sprites/models/intel/die9/9die8.bmp" 0 28
    END
  END
