  SPRITE killer 1
    FACE 0 8
      IMAGE "sprites/guns/killer/_killer8.bmp" 0 28
      IMAGE "sprites/guns/killer/_killer7.bmp" 1 28
      IMAGE "sprites/guns/killer/_killer6.bmp" 2 28
      IMAGE "sprites/guns/killer/_killer5.bmp" 3 28
      IMAGE "sprites/guns/killer/_killer4.bmp" 4 28
      IMAGE "sprites/guns/killer/_killer3.bmp" 5 28
      IMAGE "sprites/guns/killer/_killer2.bmp" 6 28
      IMAGE "sprites/guns/killer/_killer1.bmp" 7 28
    END
  END
  