  SPRITE chair 1
    FACE 0 8
      IMAGE "sprites/world/krest1/1kr1.bmp" 0 28
      IMAGE "sprites/world/krest1/1kr2.bmp" 1 28
      IMAGE "sprites/world/krest1/1kr3.bmp" 2 28
      IMAGE "sprites/world/krest1/1kr4.bmp" 3 28
      IMAGE "sprites/world/krest1/1kr5.bmp" 4 28
      IMAGE "sprites/world/krest1/1kr6.bmp" 5 28
      IMAGE "sprites/world/krest1/1kr7.bmp" 6 28
      IMAGE "sprites/world/krest1/1kr8.bmp" 7 28
    END
  END
